### ISSUE TITLE
get_nodes() in openfaas is not working when node_name is not passed

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-servless-functions#25]
The attached code prints this output:

```
[ninjato] ~/Downloads > python3 bio1.py 
Connected to DAS at 104.238.183.115:8081
{'error': 'Validation failed.\n{\n  "node_name": [\n    "Invalid data. Expected a string."\n  ]\n}'}
[{'handle': '454cd3488330ef8844208000b1ad8429', 'type': 'Schema', 'name': 'Schema:gene_association_DB_Object_ID'}]
```

**Comment by levisingularity** [comment]
![Image](https://github.com/singnet/das-servless-functions/assets/141682181/9369694b-7911-4d7d-a1d3-7583b967bcaa)

**Comment by levisingularity** [comment]
https://github.com/singnet/das-query-engine/pull/60 & https://github.com/singnet/das-servless-functions/pull/26

**Comment by levisingularity** [comment]
![Image](https://github.com/singnet/das-servless-functions/assets/141682181/bba3b02c-6b4d-4cd5-8800-4430f185579f)

@andre-senna  After the changes I've tested it locally, and it worked just fine. After you approve all the PRs I will deploy all the changes.
