### ISSUE TITLE
Create an integration test focused on Openfaas<->DAS(atomdb='redis_mongo')

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-servless-functions#30]

**Comment by levisingularity** [comment]
![Image](https://github.com/singnet/das-servless-functions/assets/141682181/6a905a84-5e72-4cfb-838a-1d9f44d754da)

Now it's possible to set up the environment locally to run automated tests.


You can see the documentation at https://github.com/singnet/das-servless-functions/tree/feat/testing

https://github.com/singnet/das-servless-functions/assets/141682181/3bd2076a-9dfb-46bf-932b-3930f44333da
