### ISSUE TITLE
Create a Makefile to run unit and integration tests using the same standard used in the query engine and atom db repos

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-servless-functions#48]
Use the same clause names, including coverage and static analysis

**Comment by levisingularity** [comment]
I've created the make file with the actions

**Comment by levisingularity** [comment]
now you can just run: `make integration-tests` for example to run the integrations tests

**Comment by levisingularity** [comment]
https://github.com/singnet/das-servless-functions/pull/49
